## Harjoitustyö

## Vaihe 1

#### Tehtävä 1. Hae Digitrafficin REST-rajapintapalvelusta (JSON-formaatissa) aktiiviset junat pääteosoitteella `/live-trains` Helsingin asemalta, joiden hakuparametrit ovat seuraavat:
* arrived_trains=10
* departed_trains=10
* include_nonstopping=False

In [1]:
import requests
import pandas as pd

In [2]:
url = "https://rata.digitraffic.fi/api/v1"
endpoint = "/live-trains"
station = "/station/HKI"
search_train = "?arrived_trains=10&departed_trains=10&include_nonstopping=False"

url2 = f"{url}{endpoint}{station}{search_train}"

req = requests.get(url2)
# req.status_code

train_info = req.json()
#train_info

#### Tehtävä 2. Tämän jälkeen lue kyseinen data Pandasin dataframeen ilman muokkaamista, jolloin sarakkeiden otsikot ovat seuraavanlaiset:

 `cancelled`,
 `commuterLineID`,
 `departureDate`,
 `operatorShortCode`,
 `operatorUICCode`,
 `runningCurrently`,
 `timeTableRows`,
 `timetableAcceptanceDate`,
 `timetableType`,
 `trainCategory`,
 `trainNumber`,
 `trainType`,
 `version`

In [3]:
#
train_df = pd.DataFrame(train_info)
train_df

,trainNumber,departureDate,operatorUICCode,operatorShortCode,trainType,trainCategory,commuterLineID,runningCurrently,cancelled,version,timetableType,timetableAcceptanceDate,timeTableRows
0,86,2023-03-14,10,vr,IC,Long-distance,,False,False,285117453638,REGULAR,2022-11-03T06:29:25.000Z,"[{'stationShortCode': 'JY', 'stationUICCode': ..."
1,89,2023-03-14,10,vr,S,Long-distance,,True,False,285117485793,REGULAR,2022-11-03T06:29:25.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
2,8158,2023-03-14,10,vr,HL,Commuter,A,False,False,285117407641,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'LPV', 'stationUICCode':..."
3,8160,2023-03-14,10,vr,HL,Commuter,A,False,False,285117465705,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'LPV', 'stationUICCode':..."
4,8165,2023-03-14,10,vr,HL,Commuter,A,True,False,285117477811,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
5,8366,2023-03-14,10,vr,HL,Commuter,E,False,False,285117411516,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'KLH', 'stationUICCode':..."
6,8482,2023-03-14,10,vr,HL,Commuter,U,False,True,285116568497,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'KKN', 'stationUICCode':..."
7,8487,2023-03-14,10,vr,HL,Commuter,U,True,False,285117472154,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
8,8580,2023-03-14,10,vr,HL,Commuter,Y,False,False,285117441540,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'STI', 'stationUICCode':..."
9,8695,2023-03-14,10,vr,HL,Commuter,P,False,False,285117444973,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
10,8697,2023-03-14,10,vr,HL,Commuter,P,False,False,285117475120,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
11,8705,2023-03-14,10,vr,HL,Commuter,P,True,False,285117480379,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
12,8706,2023-03-14,10,vr,HL,Commuter,P,True,False,285117481770,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
13,8707,2023-03-14,10,vr,HL,Commuter,P,False,False,285116340417,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
14,8892,2023-03-14,10,vr,HL,Commuter,I,False,False,285117439769,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
15,8893,2023-03-14,10,vr,HL,Commuter,I,True,False,285117465306,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
16,8894,2023-03-14,10,vr,HL,Commuter,I,True,False,285117482662,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
17,8901,2023-03-14,10,vr,HL,Commuter,I,True,False,285117476958,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
18,8931,2023-03-14,10,vr,HL,Commuter,I,False,False,285117464146,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
19,9210,2023-03-14,10,vr,HL,Commuter,K,False,False,285117444973,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'KE', 'stationUICCode': ..."
20,9214,2023-03-14,10,vr,HL,Commuter,K,False,False,285117437872,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'KE', 'stationUICCode': ..."
21,9218,2023-03-14,10,vr,HL,Commuter,K,True,False,285117485793,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'KE', 'stationUICCode': ..."
22,9237,2023-03-14,10,vr,HL,Commuter,K,True,False,285117483014,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
23,9243,2023-03-14,10,vr,HL,Commuter,K,True,False,285117483442,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
24,9355,2023-03-14,10,vr,HL,Commuter,K,False,False,285117341230,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
25,9696,2023-03-14,10,vr,HL,Commuter,R,True,False,285117485793,REGULAR,2022-11-03T06:29:25.000Z,"[{'stationShortCode': 'RI', 'stationUICCode': ..."
26,9709,2023-03-14,10,vr,HL,Commuter,R,True,False,285117479236,REGULAR,2022-11-03T06:29:25.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
27,64001,2023-03-14,10,vr,W,Shunting,,False,False,285116788942,REGULAR,2022-11-03T06:29:25.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
28,64125,2023-03-14,10,vr,W,Shunting,,False,False,285117484708,REGULAR,2022-11-03T06:29:25.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
29,64127,2023-03-14,10,vr,W,Shunting,,False,False,285116785994,REGULAR,2022-11-03T06:29:25.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."

#### Tehtävä 3. Poista kaikki muut sarakkeet paitsi `timeTableRows` ja `trainNumber`

In [4]:
#
# train_pd = train_pd[(train_pd["timeTableRows"]) & (train_pd["trainNumber"])]
# train_pd
train_df = train_df.loc[:,["trainNumber","timeTableRows"]]
train_df

    trainNumber                                      timeTableRows
0            86  [{'stationShortCode': 'JY', 'stationUICCode': ...
1            89  [{'stationShortCode': 'HKI', 'stationUICCode':...
2          8158  [{'stationShortCode': 'LPV', 'stationUICCode':...
3          8160  [{'stationShortCode': 'LPV', 'stationUICCode':...
4          8165  [{'stationShortCode': 'HKI', 'stationUICCode':...
5          8366  [{'stationShortCode': 'KLH', 'stationUICCode':...
6          8482  [{'stationShortCode': 'KKN', 'stationUICCode':...
7          8487  [{'stationShortCode': 'HKI', 'stationUICCode':...
8          8580  [{'stationShortCode': 'STI', 'stationUICCode':...
9          8695  [{'stationShortCode': 'HKI', 'stationUICCode':...
10         8697  [{'stationShortCode': 'HKI', 'stationUICCode':...
11         8705  [{'stationShortCode': 'HKI', 'stationUICCode':...
12         8706  [{'stationShortCode': 'HKI', 'stationUICCode':...
13         8707  [{'stationShortCode': 'HKI', 'stationUICCode':...
14         8892  [{'stationShortCode': 'HKI', 'stationUICCode':...
15         8893  [{'stationShortCode': 'HKI', 'stationUICCode':...
16         8894  [{'stationShortCode': 'HKI', 'stationUICCode':...
17         8901  [{'stationShortCode': 'HKI', 'stationUICCode':...
18         8931  [{'stationShortCode': 'HKI', 'stationUICCode':...
19         9210  [{'stationShortCode': 'KE', 'stationUICCode': ...
20         9214  [{'stationShortCode': 'KE', 'stationUICCode': ...
21         9218  [{'stationShortCode': 'KE', 'stationUICCode': ...
22         9237  [{'stationShortCode': 'HKI', 'stationUICCode':...
23         9243  [{'stationShortCode': 'HKI', 'stationUICCode':...
24         9355  [{'stationShortCode': 'HKI', 'stationUICCode':...
25         9696  [{'stationShortCode': 'RI', 'stationUICCode': ...
26         9709  [{'stationShortCode': 'HKI', 'stationUICCode':...
27        64001  [{'stationShortCode': 'HKI', 'stationUICCode':...
28        64125  [{'stationShortCode': 'HKI', 'stationUICCode':...
29        64127  [{'stationShortCode': 'HKI', 'stationUICCode':...

#### Tehtävä 4. Tämän jälkeen pura `timeTableRows` sarakkeen arvot jokaisesta junasta erikseen (sarakkeen arvo jokaiselle junalle sisältää useampia JSON-objekteja) ja lisää dataan mukaan junan tiedot yksilöivä `trainNumber`

In [5]:
#

t_list = []

for i in train_df["timeTableRows"]:
    for j in i:
        t_list.append(j)
# t_list
train_l = pd.DataFrame(t_list)    
train_l

,stationShortCode,stationUICCode,countryCode,type,trainStopping,commercialStop,commercialTrack,cancelled,scheduledTime,actualTime,differenceInMinutes,causes,trainNumber,trainReady,liveEstimateTime,estimateSource
0,JY,240,FI,DEPARTURE,True,True,1,False,2023-03-14T12:20:00.000Z,2023-03-14T12:21:33.000Z,2.0,[],86,"{'source': 'KUPLA', 'accepted': True, 'timesta...",NaN,NaN
1,MUU,433,FI,ARRIVAL,False,NaN,,False,2023-03-14T12:29:00.000Z,2023-03-14T12:30:24.000Z,1.0,[],86,NaN,NaN,NaN
2,MUU,433,FI,DEPARTURE,False,NaN,,False,2023-03-14T12:29:00.000Z,2023-03-14T12:30:24.000Z,1.0,[],86,NaN,NaN,NaN
3,SAA,668,FI,ARRIVAL,False,NaN,,False,2023-03-14T12:38:00.000Z,2023-03-14T12:39:08.000Z,1.0,[],86,NaN,NaN,NaN
4,SAA,668,FI,DEPARTURE,False,NaN,,False,2023-03-14T12:38:00.000Z,2023-03-14T12:39:08.000Z,1.0,[],86,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1357,ILR,1030,FI,ARRIVAL,True,True,798,False,2023-03-14T16:14:00.000Z,2023-03-14T16:15:34.000Z,2.0,[],64125,NaN,NaN,NaN
1358,HKI,1,FI,DEPARTURE,True,True,5,False,2023-03-14T16:19:00.000Z,NaN,NaN,[],64127,NaN,NaN,NaN
1359,PSL,10,FI,ARRIVAL,False,NaN,,False,2023-03-14T16:24:00.000Z,NaN,NaN,[],64127,NaN,NaN,NaN
1360,PSL,10,FI,DEPARTURE,False,NaN,,False,2023-03-14T16:24:00.000Z,NaN,NaN,[],64127,NaN,NaN,NaN
1361,ILR,1030,FI,ARRIVAL,True,True,787,False,2023-03-14T16:34:00.000Z,NaN,NaN,[],64127,NaN,NaN,NaN

#### Tehtävä 5. Pudota sitten seuraavat sarakkeet datasta: `causes`, `estimateSource`, `liveEstimateTime`, `differenceInMinutes`, `commercialStop` ja `trainReady`

In [6]:
#
train_l.drop(["causes","estimateSource","liveEstimateTime","differenceInMinutes","commercialStop","trainReady"], inplace=True, axis=1)
train_l

,stationShortCode,stationUICCode,countryCode,type,trainStopping,commercialTrack,cancelled,scheduledTime,actualTime,trainNumber
0,JY,240,FI,DEPARTURE,True,1,False,2023-03-14T12:20:00.000Z,2023-03-14T12:21:33.000Z,86
1,MUU,433,FI,ARRIVAL,False,,False,2023-03-14T12:29:00.000Z,2023-03-14T12:30:24.000Z,86
2,MUU,433,FI,DEPARTURE,False,,False,2023-03-14T12:29:00.000Z,2023-03-14T12:30:24.000Z,86
3,SAA,668,FI,ARRIVAL,False,,False,2023-03-14T12:38:00.000Z,2023-03-14T12:39:08.000Z,86
4,SAA,668,FI,DEPARTURE,False,,False,2023-03-14T12:38:00.000Z,2023-03-14T12:39:08.000Z,86
...,...,...,...,...,...,...,...,...,...,...
1357,ILR,1030,FI,ARRIVAL,True,798,False,2023-03-14T16:14:00.000Z,2023-03-14T16:15:34.000Z,64125
1358,HKI,1,FI,DEPARTURE,True,5,False,2023-03-14T16:19:00.000Z,NaN,64127
1359,PSL,10,FI,ARRIVAL,False,,False,2023-03-14T16:24:00.000Z,NaN,64127
1360,PSL,10,FI,DEPARTURE,False,,False,2023-03-14T16:24:00.000Z,NaN,64127
1361,ILR,1030,FI,ARRIVAL,True,787,False,2023-03-14T16:34:00.000Z,NaN,64127

#### Tehtävä 6. Täytä jokaisen rivin sarakkeen `actualTime` puuttuvat arvot `scheduledTime` -sarakkeen arvolla.

In [7]:
#
train_l['actualTime'].fillna(inplace=True,value=train_l['scheduledTime'])
train_l

,stationShortCode,stationUICCode,countryCode,type,trainStopping,commercialTrack,cancelled,scheduledTime,actualTime,trainNumber
0,JY,240,FI,DEPARTURE,True,1,False,2023-03-14T12:20:00.000Z,2023-03-14T12:21:33.000Z,86
1,MUU,433,FI,ARRIVAL,False,,False,2023-03-14T12:29:00.000Z,2023-03-14T12:30:24.000Z,86
2,MUU,433,FI,DEPARTURE,False,,False,2023-03-14T12:29:00.000Z,2023-03-14T12:30:24.000Z,86
3,SAA,668,FI,ARRIVAL,False,,False,2023-03-14T12:38:00.000Z,2023-03-14T12:39:08.000Z,86
4,SAA,668,FI,DEPARTURE,False,,False,2023-03-14T12:38:00.000Z,2023-03-14T12:39:08.000Z,86
...,...,...,...,...,...,...,...,...,...,...
1357,ILR,1030,FI,ARRIVAL,True,798,False,2023-03-14T16:14:00.000Z,2023-03-14T16:15:34.000Z,64125
1358,HKI,1,FI,DEPARTURE,True,5,False,2023-03-14T16:19:00.000Z,2023-03-14T16:19:00.000Z,64127
1359,PSL,10,FI,ARRIVAL,False,,False,2023-03-14T16:24:00.000Z,2023-03-14T16:24:00.000Z,64127
1360,PSL,10,FI,DEPARTURE,False,,False,2023-03-14T16:24:00.000Z,2023-03-14T16:24:00.000Z,64127
1361,ILR,1030,FI,ARRIVAL,True,787,False,2023-03-14T16:34:00.000Z,2023-03-14T16:34:00.000Z,64127

## Vaihe 2

#### Tehtävä 7. Pura tämän kansion sisällä olevan `data.html` -tiedoston `table`-elementin solujen arvot käyttäen regex-syntaksia ja yhdistä ne vaiheessa 1 luotuun dataframeen. Huom: tehtävässä tulee käyttää vain regexiä (Esim. Pandasin read_html()-metodin käyttö on kielletty)!

In [8]:
import re
import urllib.request

In [9]:
url = 'file:///C:/Users/sanni/Aida/ttc8030-harjoitukset/harjoitustyo/data.html'
html = urllib.request.urlopen(url).read()
html = html.decode()

pattern = r'<th>(.*)</th>' #th:t
pattern2 = r'<td>\s+(.*?)\s+</td>' #kaikki td:t
ths = re.findall(pattern, html)
tds = re.findall(pattern2, html)
# ths
# tds

actualtime = tds[::10]
cancelled = tds[1::10]
commercialtrack =tds[2::10]
countrycode = tds[3::10]
scheduledtime = tds[4::10]
shortcode = tds[5::10]
uiccode = tds[6::10]
trainstopping = tds[7::10]
ttype = tds[8::10]
trainnumber = tds[9::10]

generated_dataframe = pd.DataFrame({ths[5]:shortcode,
                                    ths[6]:uiccode,
                                   ths[3]:countrycode,
                                    ths[8]:ttype,
                                   ths[7]:trainstopping,
                                   ths[2]:commercialtrack,
                                   ths[1]:cancelled,
                                   ths[4]:scheduledtime,
                                   ths[0]:actualtime,
                                   ths[9]:trainnumber})

# generated_dataframe

combined_df = pd.concat([train_l, generated_dataframe])
combined_df.reset_index(inplace=True,drop=True)
combined_df

,stationShortCode,stationUICCode,countryCode,type,trainStopping,commercialTrack,cancelled,scheduledTime,actualTime,trainNumber
0,JY,240,FI,DEPARTURE,True,1,False,2023-03-14T12:20:00.000Z,2023-03-14T12:21:33.000Z,86
1,MUU,433,FI,ARRIVAL,False,,False,2023-03-14T12:29:00.000Z,2023-03-14T12:30:24.000Z,86
2,MUU,433,FI,DEPARTURE,False,,False,2023-03-14T12:29:00.000Z,2023-03-14T12:30:24.000Z,86
3,SAA,668,FI,ARRIVAL,False,,False,2023-03-14T12:38:00.000Z,2023-03-14T12:39:08.000Z,86
4,SAA,668,FI,DEPARTURE,False,,False,2023-03-14T12:38:00.000Z,2023-03-14T12:39:08.000Z,86
...,...,...,...,...,...,...,...,...,...,...
1360,PSL,10,FI,DEPARTURE,False,,False,2023-03-14T16:24:00.000Z,2023-03-14T16:24:00.000Z,64127
1361,ILR,1030,FI,ARRIVAL,True,787,False,2023-03-14T16:34:00.000Z,2023-03-14T16:34:00.000Z,64127
1362,JVS,1272,FI,DEPARTURE,False,,False,2019-08-06T04:48:00.000Z,2019-08-06T04:48:00.000Z,150
1363,R702,98998,FI,ARRIVAL,False,,False,2019-08-06T06:04:39.000Z,2019-08-06T06:04:39.000Z,150
1364,ILA,98998,FI,ARRIVAL,9,,False,2019-08-06T07:03:12.000Z,2019-08-06T07:03:12.000Z,8337

## Vaihe 3

#### Tehtävä 8. Tee SQLite tietokanta ja lisää sinne vaiheen 2 tuloksena saatu dataframe.

In [10]:
import sqlite3

In [11]:
# Tietokannan (train.db) luominen paikalliseen hakemistoon
conn = sqlite3.connect("train.db")
combined_df.to_sql(name='trains', con=conn, index=False)
conn.close()

In [12]:
# Tietokannan taulun kaikkien tietojen lukeminen
conn = sqlite3.connect('train.db')
df = pd.read_sql_query('SELECT * FROM trains', conn)
conn.close()
df

,stationShortCode,stationUICCode,countryCode,type,trainStopping,commercialTrack,cancelled,scheduledTime,actualTime,trainNumber
0,JY,240,FI,DEPARTURE,1,1,0,2023-03-14T12:20:00.000Z,2023-03-14T12:21:33.000Z,86
1,MUU,433,FI,ARRIVAL,0,,0,2023-03-14T12:29:00.000Z,2023-03-14T12:30:24.000Z,86
2,MUU,433,FI,DEPARTURE,0,,0,2023-03-14T12:29:00.000Z,2023-03-14T12:30:24.000Z,86
3,SAA,668,FI,ARRIVAL,0,,0,2023-03-14T12:38:00.000Z,2023-03-14T12:39:08.000Z,86
4,SAA,668,FI,DEPARTURE,0,,0,2023-03-14T12:38:00.000Z,2023-03-14T12:39:08.000Z,86
...,...,...,...,...,...,...,...,...,...,...
1360,PSL,10,FI,DEPARTURE,0,,0,2023-03-14T16:24:00.000Z,2023-03-14T16:24:00.000Z,64127
1361,ILR,1030,FI,ARRIVAL,1,787,0,2023-03-14T16:34:00.000Z,2023-03-14T16:34:00.000Z,64127
1362,JVS,1272,FI,DEPARTURE,False,,False,2019-08-06T04:48:00.000Z,2019-08-06T04:48:00.000Z,150
1363,R702,98998,FI,ARRIVAL,False,,False,2019-08-06T06:04:39.000Z,2019-08-06T06:04:39.000Z,150
1364,ILA,98998,FI,ARRIVAL,9,,False,2019-08-06T07:03:12.000Z,2019-08-06T07:03:12.000Z,8337